---
# role: tftpd
# file: molecule/resources/playbooks/converge.yml

- name: "Molecule | converge | tftpd"
  hosts: all
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
