---
# role: tftpd
# file: molecule/resources/playbooks/prepare.yml

- name: "Molecule | prepare | tftpd"
  hosts: all
  gather_facts: true
  tasks:
    - name: "TFTPD | Refresh APT package metadata"
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.pkg_mgr == 'apt'

    - name: "TFTPD | Refresh DNF package metadata"
      become: true
      become_user: root
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_facts.pkg_mgr in ['dnf', 'dnf5']

    - name: "TFTPD | Refresh Zypper package metadata"
      become: true
      become_user: root
      community.general.zypper_repository:
        repo: '*'
        runrefresh: true
      when: ansible_facts.pkg_mgr == 'zypper'
